
const axios = require('axios');

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
// ✅ ใช้ Gemini 3 Flash (ใหม่ล่าสุด)
const MODEL = 'gemini-3-flash-preview';
const GEMINI_API = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;

async function summarizeAllChatsForDate(allMessages) {
  try {
    if (allMessages.length === 0) {
      return {
        summary: 'ไม่มีข้อความในวันนี้',
        messageCount: 0,
        groupCount: 0
      };
    }

    const groupedMessages = {};
    
    allMessages.forEach(m => {
      const key = m.groupId || `private_${m.userId}`;
      if (!groupedMessages[key]) {
        groupedMessages[key] = {
          name: m.group?.groupName || m.user?.displayName || 'Unknown',
          isPrivate: !m.groupId,
          messages: []
        };
      }
      groupedMessages[key].messages.push(m);
    });

    let chatSummaryText = '';
    
    Object.entries(groupedMessages).forEach(([key, data]) => {
      const groupName = data.isPrivate ? `แชทส่วนตัว: ${data.name}` : `กลุ่ม: ${data.name}`;
      chatSummaryText += `\n\n=== ${groupName} (${data.messages.length} ข้อความ) ===\n`;
      
      data.messages.forEach(m => {
        const sender = m.user?.displayName || 'Unknown';
        const time = new Date(m.timestamp).toLocaleTimeString('th-TH', { 
          hour: '2-digit', 
          minute: '2-digit' 
        });

        let content = '';
        if (m.messageType === 'text') {
          content = m.text;
        } else if (m.messageType === 'image') {
          content = `[ส่งรูป ${m.metadata?.imageCount || 1} รูป]`;
        } else if (m.messageType === 'sticker') {
          content = '[ส่งสติกเกอร์]';
        } else if (m.messageType === 'video') {
          content = '[ส่งวิดีโอ]';
        } else if (m.messageType === 'file') {
          content = `[ส่งไฟล์: ${m.metadata?.fileName}]`;
        } else if (m.messageType === 'location') {
          content = `[แชร์ตำแหน่ง: ${m.metadata?.address}]`;
        }

        chatSummaryText += `[${time}] ${sender}: ${content}\n`;
      });
    });

    console.log('📝 Summarizing with Gemini 3:', allMessages.length, 'messages');

    const prompt = `คุณเป็นผู้ช่วยที่เชี่ยวชาญในการสรุปบทสนทนา กรุณาสรุปบทสนทนาทั้งหมดในวันนี้เป็นภาษาไทยที่อ่านง่าย ใช้รูปแบบดังนี้:

📊 **ภาพรวมวันนี้**
สรุปสั้นๆ 2-3 ประโยค ว่าวันนี้มีกิจกรรมอะไรบ้างในภาพรวม

📌 **สรุปแต่ละกลุ่ม/แชท**

1️⃣ **[ชื่อกลุ่ม/แชท]**
- หัวข้อหลัก: ...
- ประเด็นสำคัญ: ...

✨ **Highlights วันนี้**
- สิ่งที่น่าสนใจที่สุด

⚠️ **สิ่งที่ต้องติดตาม**
- งานที่ยังค้างอยู่ (ถ้ามี)

บทสนทนาที่ต้องสรุป:
${chatSummaryText}`;

    const response = await axios.post(
      GEMINI_API,
      {
        contents: [{
          parts: [{ text: prompt }]
        }]
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': GEMINI_API_KEY
        }
      }
    );

    const summary = response.data.candidates[0].content.parts[0].text;
    console.log('✅ Summary generated by Gemini 3');

    return {
      summary,
      messageCount: allMessages.length,
      groupCount: Object.keys(groupedMessages).length,
      model: 'Gemini 3 Flash'
    };

  } catch (error) {
    console.error('❌ Gemini Error:', error.message);
    
    if (error.response) {
      console.error('Response status:', error.response.status);
      console.error('Response data:', JSON.stringify(error.response.data, null, 2));
    }
    
    if (error.response?.status === 404) {
      throw new Error('Model ไม่พบ: ' + (error.response.data.error?.message || 'ตรวจสอบชื่อ model'));
    }
    
    if (error.response?.status === 400) {
      throw new Error('คำขอไม่ถูกต้อง: ' + (error.response.data.error?.message || ''));
    }
    
    if (error.response?.status === 429) {
      throw new Error('ใช้งาน API เกินจำนวนที่กำหนด กรุณารอสักครู่');
    }
    
    throw new Error(error.response?.data?.error?.message || error.message);
  }
}

module.exports = { summarizeAllChatsForDate };